FROM --platform=linux/amd64 python@sha256:2c941e860699f878900b0edc2403613c234d4b32eda3cc9fa7036991a2a63c4a

RUN pip install --no-cache-dir anyio==4.10.0 attrs==26.1.0 certifi==2025.8.3 h11==0.16.0 hatch-fancy-pypi-readme==25.1.0 hatchling==1.27.0 httpcore==1.0.9 idna==3.10 iniconfig==2.3.0 outcome==1.3.0.post0 packaging==26.3 pathspec==1.1.1 pluggy==1.6.0 pygments==2.21.0 pytest==8.4.1 sniffio==1.3.1 sortedcontainers==2.4.0 trio==0.31.0 trove-classifiers==2026.6.1.19 typing-extensions==4.16.0

WORKDIR /workspace
