#!/usr/bin/env bash
# Oracle only: fetch the frozen revision from the exact authorised host, assert
# the commit, verify the archive digest, then install the dependency-free
# contract package shape published by the public instruction.
set -euo pipefail

UPSTREAM_URL='https://github.com/dtolnay/semver'
UPSTREAM_REVISION='6ed8561154715b2c34df417a2052597d586f2c43'
SOURCE_SHA256='193fa1e8e7fd3f5bd3f5fcf911df523b4d1cd59c33fba7a079bec9dfaf761594'
SOURCE_DIR=/tmp/semver-oracle-upstream
SOURCE_ARCHIVE=/tmp/semver-oracle-source.tar
EXTRACT_DIR=/tmp/semver-oracle-source

rm -rf "$SOURCE_DIR" "$SOURCE_ARCHIVE" "$EXTRACT_DIR"
git init "$SOURCE_DIR" >/dev/null
git -C "$SOURCE_DIR" remote add origin "$UPSTREAM_URL"
git -C "$SOURCE_DIR" fetch --depth 1 origin "$UPSTREAM_REVISION" >/dev/null
test "$(git -C "$SOURCE_DIR" rev-parse FETCH_HEAD)" = "$UPSTREAM_REVISION"
git -C "$SOURCE_DIR" archive --format=tar --prefix=semver/ FETCH_HEAD > "$SOURCE_ARCHIVE"
echo "$SOURCE_SHA256  $SOURCE_ARCHIVE" | sha256sum --check --strict
mkdir -p "$EXTRACT_DIR"
tar -xf "$SOURCE_ARCHIVE" -C "$EXTRACT_DIR"

find /workspace -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
cp -a "$EXTRACT_DIR/semver/src" /workspace/src
cp -a "$EXTRACT_DIR/semver/build.rs" /workspace/build.rs
cp -a "$EXTRACT_DIR/semver/LICENSE-MIT" /workspace/LICENSE-MIT
cp -a "$EXTRACT_DIR/semver/LICENSE-APACHE" /workspace/LICENSE-APACHE

# The published manifest declares an optional serde integration that cannot be
# resolved inside the dependency-free offline closure, so install the
# dependency-free contract manifest the instruction publishes instead. No
# behaviour covered by the task API changes as a result.
cat > /workspace/Cargo.toml <<'CONTRACT'
[package]
name = "semver"
version = "1.0.27"
edition = "2018"
rust-version = "1.61"
license = "MIT OR Apache-2.0"
description = "Parser and evaluator for Cargo's flavor of Semantic Versioning"

[features]
default = ["std"]
std = []

[lib]
path = "src/lib.rs"

[dependencies]
CONTRACT
cat > /workspace/Cargo.lock <<'LOCKFILE'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "semver"
version = "1.0.27"
LOCKFILE
