#!/usr/bin/env bash
set -euo pipefail
mkdir -p /workspace/src/main/java/de/svenkubiak/http /workspace/src/main/java/de/svenkubiak/utils
printf '%s\n' '<project><modelVersion>4.0.0</modelVersion><groupId>de.svenkubiak</groupId><artifactId>simple-http</artifactId><version>1</version></project>' > /workspace/pom.xml
cat > /workspace/src/main/java/de/svenkubiak/http/Result.java <<'JAVA'
package de.svenkubiak.http; public class Result { private final java.util.Map<String,String> h=new java.util.HashMap<>(); private String b=""; private byte[] bytes; private int s=-1; public static Result create(){return new Result();} public Result withBody(String v){b=v==null||v.isEmpty()?"":v;return this;} public Result withBinaryBody(byte[] v){bytes=v;return this;} public Result withStatus(int v){s=v;return this;} public Result withHeader(String k,String v){h.put(k,v);return this;} public String body(){return b;} public byte[] binaryBody(){return bytes==null?null:java.util.Arrays.copyOf(bytes,bytes.length);} public String header(String k){return h.get(k);} public String error(){return b;} public int status(){return s;} public boolean isValid(){return de.svenkubiak.utils.Utils.isSuccessCode(s);} public boolean isValid(int... v){for(int x:v)if(x==s)return true;return false;} }
JAVA
cat > /workspace/src/main/java/de/svenkubiak/utils/Utils.java <<'JAVA'
package de.svenkubiak.utils; public final class Utils { private Utils(){} public static boolean isSuccessCode(int v){return v>=200&&v<=208||v==226;} public static String getFormDataAsString(java.util.Map<String,String> m){var b=new StringBuilder();for(var e:m.entrySet()){if(!b.isEmpty())b.append('&');b.append(java.net.URLEncoder.encode(e.getKey(),java.nio.charset.StandardCharsets.UTF_8)).append('=').append(java.net.URLEncoder.encode(e.getValue(),java.nio.charset.StandardCharsets.UTF_8));}return b.toString();} public static String clean(String s){return s.replaceAll("[^A-Za-z0-9 ]","");} public static java.net.URI toAllowedUri(String s)throws java.net.URISyntaxException{var u=new java.net.URI(s);if(!"http".equalsIgnoreCase(u.getScheme())&&!"https".equalsIgnoreCase(u.getScheme()))throw new java.net.URISyntaxException(s,"Only http and https URLs are allowed");return u;} }
JAVA
