CASES = [
    ("basic-object", """import jiter\nassert jiter.from_json(b'{\"a\": 1, \"b\": [true, null]}') == {'a': 1, 'b': [True, None]}\nresult = True"""),
    ("basic-array", """import jiter\nassert jiter.from_json(b'[1, -2, 3]') == [1, -2, 3]\nresult = True"""),
    ("basic-booleans", """import jiter\nassert jiter.from_json(b'true') is True and jiter.from_json(b'false') is False\nresult = True"""),
    ("basic-null", """import jiter\nassert jiter.from_json(b'null') is None\nresult = True"""),
    ("basic-whitespace", """import jiter\nassert jiter.from_json(b'  {\"x\": 1}  ') == {'x': 1}\nresult = True"""),
    ("number-float", """import jiter\nassert jiter.from_json(b'1.25') == 1.25\nresult = True"""),
    ("number-decimal", """from decimal import Decimal\nimport jiter\nassert jiter.from_json(b'123.456e2', float_mode='decimal') == Decimal('12345.6')\nassert isinstance(jiter.from_json(b'1', float_mode='decimal'), int)\nresult = True"""),
    ("number-lossless", """import jiter\nvalue = jiter.from_json(b'123.456e2', float_mode='lossless-float')\nassert type(value).__name__ == 'LosslessFloat' and bytes(value) == b'123.456e2'\nresult = True"""),
    ("number-nonfinite", """import math, jiter\nassert math.isnan(jiter.from_json(b'NaN'))\nassert jiter.from_json(b'Infinity') == float('inf')\nresult = True"""),
    ("number-reject-nonfinite", """import jiter\ntry: jiter.from_json(b'[NaN]', allow_inf_nan=False)\nexcept ValueError: result = True\nelse: result = False"""),
    ("partial-array", """import jiter\nraw = b'[\"a\", true, null, 1, \"unfinished'\nassert jiter.from_json(raw, partial_mode=True) == ['a', True, None, 1]\nresult = True"""),
    ("partial-array-trailing", """import jiter\nraw = b'[\"a\", true, null, 1, \"unfinished'\nassert jiter.from_json(raw, partial_mode='trailing-strings') == ['a', True, None, 1, 'unfinished']\nresult = True"""),
    ("partial-object", """import jiter\nassert jiter.from_json(b'{\"a\": 1, \"b\": 2, \"c', partial_mode=True) == {'a': 1, 'b': 2}\nresult = True"""),
    ("partial-object-trailing", """import jiter\nassert jiter.from_json(b'{\"a\": 1, \"b\": \"part', partial_mode='trailing-strings') == {'a': 1, 'b': 'part'}\nresult = True"""),
    ("partial-utf8", """import jiter\nassert jiter.from_json(b'\"abc\\xe2\\x82', partial_mode='trailing-strings') == 'abc'\nresult = True"""),
    ("error-eof", """import jiter\ntry: jiter.from_json(b'[1')\nexcept ValueError: result = True\nelse: result = False"""),
    ("error-invalid", """import jiter\ntry: jiter.from_json(b'xx')\nexcept ValueError: result = True\nelse: result = False"""),
    ("error-trailing", """import jiter\ntry: jiter.from_json(b'1 2')\nexcept ValueError: result = True\nelse: result = False"""),
    ("error-duplicate", """import jiter\ntry: jiter.from_json(b'{\"x\": 1, \"x\": 2}', catch_duplicate_keys=True)\nexcept ValueError as exc: assert 'duplicate' in str(exc).lower(); result = True\nelse: result = False"""),
    ("error-invalid-mode", """import jiter\ntry: jiter.from_json(b'1', float_mode='bad')\nexcept (ValueError, TypeError): result = True\nelse: result = False"""),
    ("string-unicode", """import jiter\nassert jiter.from_json('{\"中文\": \"€\"}'.encode()) == {'中文': '€'}\nresult = True"""),
    ("string-escapes", """import jiter\nvalue = jiter.from_json(b'\"a\\\\n\\\\t\\\\\\\\\\\\\"b\"')\nassert value == 'a' + chr(10) + chr(9) + chr(92) + chr(34) + 'b'\nresult = True"""),
    ("string-surrogate", """import jiter\nassert jiter.from_json(b'\"\\ud83d\\udca9\"') == '💩'\nresult = True"""),
    ("nested-values", """import jiter\nassert jiter.from_json(b'{\"a\": [{\"b\": [1, 2, 3]}]}') == {'a': [{'b': [1, 2, 3]}]}\nresult = True"""),
    ("cache-all", """import jiter\njiter.cache_clear(); jiter.from_json(b'{\"foo\": \"bar\", \"spam\": 3}', cache_mode='all')\nassert jiter.cache_usage() == 3\nresult = True"""),
    ("cache-keys", """import jiter\njiter.cache_clear(); jiter.from_json(b'{\"foo\": \"bar\", \"spam\": 3}', cache_mode='keys')\nassert jiter.cache_usage() == 2\nresult = True"""),
    ("cache-none", """import jiter\njiter.cache_clear(); jiter.from_json(b'{\"foo\": \"bar\", \"spam\": 3}', cache_mode='none')\nassert jiter.cache_usage() == 0\nresult = True"""),
    ("cache-clear", """import jiter\njiter.from_json(b'\"cached\"'); jiter.cache_clear()\nassert jiter.cache_usage() == 0\nresult = True"""),
    ("lossless-bytes", """import jiter\nf = jiter.LosslessFloat(b'123.45')\nassert bytes(f) == b'123.45' and str(f) == '123.45' and repr(f) == 'LosslessFloat(123.45)'\nresult = True"""),
    ("lossless-convert", """from decimal import Decimal\nimport jiter\nf = jiter.LosslessFloat(b'123.45')\nassert float(f) == 123.45 and f.as_decimal() == Decimal('123.45')\nresult = True"""),
    ("lossless-scientific", """import jiter\nf = jiter.LosslessFloat(b'1.23e4')\nassert float(f) == 12300 and str(f) == '1.23e4'\nresult = True"""),
    ("lossless-invalid", """import jiter\ntry: jiter.LosslessFloat(b'1.2x')\nexcept ValueError: result = True\nelse: result = False"""),
]
