from __future__ import annotations

SCENARIOS = [
    ("version", "import oauthlib; result=oauthlib.__version__", "3.4.0"),
    ("debug", "import oauthlib; a=oauthlib.get_debug(); oauthlib.set_debug(True); b=oauthlib.get_debug(); oauthlib.set_debug(False); result=[a,b,oauthlib.get_debug()]", [False, True, False]),
    ("metadata", "import importlib.metadata; result=importlib.metadata.version('oauthlib')", "3.4.0"),
    ("quote", "from oauthlib.common import quote; result=quote('a b/~')", "a%20b/~"),
    ("unquote", "from oauthlib.common import unquote; result=unquote('caf%C3%A9%20x')", "café x"),
    ("urlencode", "from oauthlib.common import urlencode; result=urlencode([('a','x y'),('a','z'),('n',3)])", "a=x+y&a=z&n=3"),
    ("urldecode", "from oauthlib.common import urldecode; result=urldecode('a=x+y&a=z&blank=')", [["a", "x y"], ["a", "z"], ["blank", ""]]),
    ("malformed-escape", "from oauthlib.common import urldecode;\ntry: urldecode('a=%ZZ')\nexcept Exception as e: result=[type(e).__name__,str(e)]", ["ValueError", "Invalid hex encoding in query string."]),
    ("extract-params", "from oauthlib.common import extract_params; result=extract_params('a=1&a=2')", [["a", "1"], ["a", "2"]]),
    ("add-query", "from oauthlib.common import add_params_to_qs; result=add_params_to_qs('a=1',[('b','x y'),('a','2')])", "a=1&b=x+y&a=2"),
    ("add-uri", "from oauthlib.common import add_params_to_uri; result=add_params_to_uri('https://e.test/p?a=1#f',[('b','x y')])", "https://e.test/p?a=1&b=x+y#f"),
    ("case-insensitive-dict", "from oauthlib.common import CaseInsensitiveDict; d=CaseInsensitiveDict({'Content-Type':'text/plain'}); d['X-Test']='one'; d.update({'x-test':'two'}); result=[d['content-type'],d.get('X-TEST'),d['x-test'],sorted(d.items())]", ["text/plain", "two", "two", [["Content-Type", "text/plain"], ["X-Test", "one"], ["x-test", "two"]]]),
    ("request", "from oauthlib.common import Request; r=Request('https://e.test/p?a=1&a=2&b=',http_method='post',body='c=3',headers={'X':'y'}); result=[r.uri,r.http_method,r.uri_query,r.uri_query_params,r.duplicate_params,r.decoded_body,r.headers['x']]", ["https://e.test/p?a=1&a=2&b=", "post", "a=1&a=2&b=", [["a", "1"], ["a", "2"], ["b", ""]], ["a"], [["c", "3"]], "y"]),
    ("oauth1-escape", "from oauthlib.oauth1.rfc5849.utils import escape,unescape; x=escape('Ladies + Gentlemen'); result=[x,unescape(x)]", ["Ladies%20%2B%20Gentlemen", "Ladies + Gentlemen"]),
    ("oauth1-auth-header", "from oauthlib.oauth1.rfc5849.utils import parse_authorization_header; result=parse_authorization_header('OAuth realm=\"Example\", oauth_consumer_key=\"key%201\", oauth_signature=\"abc%3D\"')", [["realm", "Example"], ["oauth_consumer_key", "key%201"], ["oauth_signature", "abc%3D"]]),
    ("oauth1-filter", "from oauthlib.oauth1.rfc5849.utils import filter_oauth_params; result=filter_oauth_params([('a','1'),('oauth_nonce','n'),('oauth_token','t')])", [["oauth_nonce", "n"], ["oauth_token", "t"]]),
    ("oauth1-headers", "from oauthlib.oauth1.rfc5849.parameters import prepare_headers; result=prepare_headers([('oauth_nonce','n n'),('oauth_consumer_key','key')],{'X-Test':'v'},realm='Example')", {"Authorization": "OAuth realm=\"Example\", oauth_nonce=\"n%20n\", oauth_consumer_key=\"key\"", "X-Test": "v"}),
    ("oauth1-body", "from oauthlib.oauth1.rfc5849.parameters import prepare_form_encoded_body; result=prepare_form_encoded_body([('oauth_nonce','n')],[('a','1')])", [["a", "1"], ["oauth_nonce", "n"]]),
    ("oauth1-uri", "from oauthlib.oauth1.rfc5849.parameters import prepare_request_uri_query; result=prepare_request_uri_query([('oauth_nonce','n n')],'https://e.test/p?a=1#f')", "https://e.test/p?a=1&oauth_nonce=n+n#f"),
    ("oauth1-base-uri", "from oauthlib.oauth1.rfc5849.signature import base_string_uri; result=base_string_uri('HTTPS://EXAMPLE.COM:443/r%20v/X?id=123')", "https://example.com/r%20v/X"),
    ("oauth1-collect", "from oauthlib.oauth1.rfc5849.signature import collect_parameters; result=collect_parameters('a=1&oauth_signature=x','b=2',{'Authorization':'OAuth realm=\"r\", oauth_nonce=\"n\"'})", [["a", "1"], ["oauth_nonce", "n"], ["b", "2"]]),
    ("oauth1-normalize", "from oauthlib.oauth1.rfc5849.signature import normalize_parameters; result=normalize_parameters([('b','x y'),('a','2'),('a','1'),('a','')])", "a=&a=1&a=2&b=x%20y"),
    ("oauth1-base-string", "from oauthlib.oauth1.rfc5849.signature import signature_base_string; result=signature_base_string('post','https://example.com/r','a%3D1%26b%3Dx%2520y')", "POST&https%3A%2F%2Fexample.com%2Fr&a%253D1%2526b%253Dx%252520y"),
    ("oauth1-hmac-sha1", "from oauthlib.oauth1.rfc5849.signature import sign_hmac_sha1; result=sign_hmac_sha1('POST&https%3A%2F%2Fexample.com&a%3D1','cs','ts')", "NLEve+a3xr1Pq/COxzDKLsF6KJg="),
    ("oauth1-hmac-sha256", "from oauthlib.oauth1.rfc5849.signature import sign_hmac_sha256; result=sign_hmac_sha256('POST&https%3A%2F%2Fexample.com&a%3D1','cs','ts')", "0wGQiHtfuQB7qSYBm2mYz+r6CnyTJEFQf0vzDLgwPHY="),
    ("oauth1-plaintext", "from oauthlib.oauth1.rfc5849.signature import sign_plaintext; result=sign_plaintext('c s','t&s')", "c%20s&t%26s"),
    ("oauth2-list-scope", "from oauthlib.oauth2.rfc6749.utils import list_to_scope; result=list_to_scope(['read','write'])", "read write"),
    ("oauth2-scope-list", "from oauthlib.oauth2.rfc6749.utils import scope_to_list; result=scope_to_list('read  write')", ["read", "", "write"]),
    ("oauth2-uri-params", "from oauthlib.oauth2.rfc6749.utils import params_from_uri; result=params_from_uri('https://e.test/cb?code=abc&scope=read%20write&code=def')", {"code": "def", "scope": ["read", "write"]}),
    ("oauth2-host", "from oauthlib.oauth2.rfc6749.utils import host_from_uri; result=host_from_uri('https://EXAMPLE.com:443/x')", ["EXAMPLE.com", "443"]),
    ("oauth2-secure", "from oauthlib.oauth2.rfc6749.utils import is_secure_transport; result=[is_secure_transport('https://e.test'),is_secure_transport('http://e.test'),is_secure_transport('urn:example:test')]", [True, False, False]),
    ("oauth2-grant-uri", "from oauthlib.oauth2.rfc6749.parameters import prepare_grant_uri; result=prepare_grant_uri('https://e.test/auth?existing=1','cid','code',redirect_uri='https://app/cb',scope=['read','write'],state='s 1')", "https://e.test/auth?existing=1&response_type=code&client_id=cid&redirect_uri=https%3A%2F%2Fapp%2Fcb&scope=read+write&state=s+1"),
    ("oauth2-token-request", "from oauthlib.oauth2.rfc6749.parameters import prepare_token_request; result=prepare_token_request('authorization_code',code='abc',redirect_uri='https://app/cb',client_id='cid',code_verifier='ver')", "grant_type=authorization_code&client_id=cid&code_verifier=ver&code=abc&redirect_uri=https%3A%2F%2Fapp%2Fcb"),
    ("oauth2-revocation", "from oauthlib.oauth2.rfc6749.parameters import prepare_token_revocation_request; result=prepare_token_revocation_request('https://e.test/revoke','tok',client_id='cid')", ["https://e.test/revoke", {"Content-Type": "application/x-www-form-urlencoded"}, "token=tok&token_type_hint=access_token&client_id=cid"]),
    ("oauth2-auth-response", "from oauthlib.oauth2.rfc6749.parameters import parse_authorization_code_response; result=parse_authorization_code_response('https://app/cb?code=abc&state=s1',state='s1')", {"code": "abc", "state": "s1"}),
    ("oauth2-token-response", "from oauthlib.oauth2.rfc6749.parameters import parse_token_response; d=parse_token_response('{\"access_token\":\"tok\",\"token_type\":\"Bearer\",\"expires_in\":3600,\"scope\":\"read write\"}'); result=sorted((k,type(v).__name__,v) for k,v in d.items() if k!='expires_at')", [["access_token", "str", "tok"], ["expires_in", "int", 3600], ["scope", "list", ["read", "write"]], ["token_type", "str", "Bearer"]]),
    ("oauth2-token-delta", "from oauthlib.oauth2.rfc6749.tokens import OAuth2Token; t=OAuth2Token({'scope':'read write','access_token':'x'},old_scope='read'); result=[t.scope_changed,sorted(t.old_scopes),sorted(t.scopes),sorted(t.missing_scopes),sorted(t.additional_scopes)]", [True, ["read"], ["read", "write"], [], ["write"]]),
    ("oauth2-bearer-headers", "from oauthlib.oauth2.rfc6749.tokens import prepare_bearer_headers; result=prepare_bearer_headers('tok',{'X':'y'})", {"Authorization": "Bearer tok", "X": "y"}),
    ("oauth2-bearer-body", "from oauthlib.oauth2.rfc6749.tokens import prepare_bearer_body; result=prepare_bearer_body('tok','a=1')", "a=1&access_token=tok"),
    ("oauth2-bearer-uri", "from oauthlib.oauth2.rfc6749.tokens import prepare_bearer_uri; result=prepare_bearer_uri('tok','https://e.test/r?x=1')", "https://e.test/r?x=1&access_token=tok"),
    ("web-client-uri", "from oauthlib.oauth2 import WebApplicationClient; c=WebApplicationClient('cid'); result=c.prepare_request_uri('https://e.test/auth',redirect_uri='https://app/cb',scope=['read'],state='s')", "https://e.test/auth?response_type=code&client_id=cid&redirect_uri=https%3A%2F%2Fapp%2Fcb&scope=read&state=s"),
    ("backend-client-body", "from oauthlib.oauth2 import BackendApplicationClient; c=BackendApplicationClient('cid'); result=c.prepare_request_body(scope=['read','write'])", "grant_type=client_credentials&scope=read+write"),
]
