"""Private deterministic contract verifier for requests-oauthlib."""
from __future__ import annotations
import json
from nl2repobench.verification.candidate_client import execute_script
SCENARIOS = [
    ("version_exports", 'import requests_oauthlib as p\nresult = p.__version__ == "2.0.0" and all(hasattr(p, n) for n in ("OAuth1", "OAuth1Session", "OAuth2", "OAuth2Session", "TokenUpdated"))'),
    ("package_metadata", 'from importlib.metadata import version\nresult = version("requests-oauthlib") == "2.0.0"'),
    ("oauth1_header_signing", 'from requests import Request\nfrom requests_oauthlib import OAuth1\nr = Request("POST", "https://service.example/path", data={"a":"b"}).prepare()\nOAuth1("client", client_secret="secret")(r)\nresult = r.headers.get("Content-Type") == b"application/x-www-form-urlencoded" and b"OAuth " in r.headers.get("Authorization", b"") and b"oauth_signature=" in r.headers.get("Authorization", b"")'),
    ("oauth1_query_signing", 'from requests import Request\nfrom requests_oauthlib import OAuth1\nfrom oauthlib.oauth1 import SIGNATURE_TYPE_QUERY\nr = Request("GET", "https://service.example/path?keep=yes").prepare()\nOAuth1("client", client_secret="secret", signature_type=SIGNATURE_TYPE_QUERY)(r)\nresult = "keep=yes" in r.url and "oauth_signature=" in r.url and "oauth_consumer_key=client" in r.url'),
    ("oauth1_session_token", 'from requests_oauthlib import OAuth1Session\ns = OAuth1Session("client", client_secret="secret")\ns.token = {"oauth_token":"token", "oauth_token_secret":"secret", "oauth_verifier":"verify"}\nresult = s.token == {"oauth_token":"token", "oauth_token_secret":"secret", "oauth_verifier":"verify"} and s.authorized is True'),
    ("oauth1_authorization_url", 'from urllib.parse import parse_qs, urlparse\nfrom requests_oauthlib import OAuth1Session\nurl = OAuth1Session("client").authorization_url("https://provider.example/authorize?keep=yes", request_token="token", prompt="login")\nresult = parse_qs(urlparse(url).query) == {"keep":["yes"], "oauth_token":["token"], "prompt":["login"]}'),
    ("oauth1_parse_response", 'from requests_oauthlib import OAuth1Session\ns = OAuth1Session("client", client_secret="secret")\nt = s.parse_authorization_response("https://app.example/callback?oauth_token=one&oauth_token_secret=two&oauth_verifier=three")\nresult = t == {"oauth_token":"one", "oauth_token_secret":"two", "oauth_verifier":"three"} and s.token == t'),
    ("oauth1_missing_verifier", 'from requests_oauthlib import OAuth1Session\nfrom requests_oauthlib.oauth1_session import VerifierMissing\ntry:\n    OAuth1Session("client", client_secret="secret").fetch_access_token("https://provider.example/token")\nexcept VerifierMissing:\n    result = True\nelse:\n    result = False'),
    ("oauth1_fetch_token", 'from types import SimpleNamespace\nfrom requests_oauthlib import OAuth1Session\ns = OAuth1Session("client", client_secret="secret", callback_uri="https://app.example/callback")\ns.post = lambda *a, **k: SimpleNamespace(status_code=200, text="oauth_token=one&oauth_token_secret=two")\nt = s.fetch_request_token("https://provider.example/request", realm=["read", "write"])\nresult = t == {"oauth_token":"one", "oauth_token_secret":"two"} and s._client.client.callback_uri is None'),
    ("oauth2_auth_header", 'from requests import Request\nfrom requests_oauthlib import OAuth2\nr = Request("GET", "https://api.example/resource").prepare()\nOAuth2("client", token={"access_token":"token", "token_type":"Bearer"})(r)\nresult = r.headers.get("Authorization") == "Bearer token"'),
    ("oauth2_auth_insecure", 'from requests import Request\nfrom oauthlib.oauth2 import InsecureTransportError\nfrom requests_oauthlib import OAuth2\ntry:\n    OAuth2("client", token={"access_token":"token", "token_type":"Bearer"})(Request("GET", "http://api.example/resource").prepare())\nexcept InsecureTransportError:\n    result = True\nelse:\n    result = False'),
    ("oauth2_session_properties", 'from requests_oauthlib import OAuth2Session\ns = OAuth2Session("client", scope=["read"], redirect_uri="https://app.example/callback", token={"access_token":"token", "token_type":"Bearer"})\nresult = s.client_id == "client" and s.scope == ["read"] and s.access_token == "token" and s.authorized is True'),
    ("oauth2_authorization_url", 'from urllib.parse import parse_qs, urlparse\nfrom requests_oauthlib import OAuth2Session\nurl, state = OAuth2Session("client", scope=["read", "write"], redirect_uri="https://app.example/callback", state="fixed").authorization_url("https://provider.example/authorize", audience="api")\nq = parse_qs(urlparse(url).query)\nresult = state == "fixed" and q["client_id"] == ["client"] and q["redirect_uri"] == ["https://app.example/callback"] and q["scope"] == ["read write"] and q["state"] == ["fixed"] and q["audience"] == ["api"]'),
    ("oauth2_pkce", 'from urllib.parse import parse_qs, urlparse\nfrom requests_oauthlib import OAuth2Session\ns = OAuth2Session("client", pkce="S256", state="fixed")\nurl, state = s.authorization_url("https://provider.example/authorize")\nq = parse_qs(urlparse(url).query)\nresult = state == "fixed" and q["code_challenge_method"] == ["S256"] and len(q["code_challenge"][0]) > 20 and len(s._code_verifier) >= 43'),
    ("oauth2_invalid_pkce", 'from requests_oauthlib import OAuth2Session\ntry:\n    OAuth2Session("client", pkce="unsupported")\nexcept AttributeError:\n    result = True\nelse:\n    result = False'),
    ("oauth2_token_fragment", 'from oauthlib.oauth2 import MobileApplicationClient\nfrom requests_oauthlib import OAuth2Session\ns = OAuth2Session(client=MobileApplicationClient("client"), state="fixed")\nt = s.token_from_fragment("https://app.example/callback#access_token=token&token_type=Bearer&state=fixed")\nresult = t["access_token"] == "token" and t["token_type"] == "Bearer" and s.token == t'),
    ("oauth2_fetch_token", 'from types import SimpleNamespace\nfrom requests_oauthlib import OAuth2Session\ns = OAuth2Session("client", redirect_uri="https://app.example/callback")\nseen = {}\ndef fake_request(**k):\n    seen.update(k)\n    return SimpleNamespace(status_code=200, text="{\\"access_token\\":\\"token\\",\\"token_type\\":\\"Bearer\\"}", headers={}, request=SimpleNamespace(url=k["url"], headers={}, body=""))\ns.request = fake_request\nt = s.fetch_token("https://provider.example/token", code="code", include_client_id=True, client_secret="secret")\nresult = t == {"access_token":"token", "token_type":"Bearer"} and seen["data"]["code"] == "code" and seen["data"]["client_id"] == "client"'),
    ("oauth2_refresh_token", 'from types import SimpleNamespace\nfrom requests_oauthlib import OAuth2Session\ns = OAuth2Session("client", token={"access_token":"old", "token_type":"Bearer", "refresh_token":"refresh"})\ns.post = lambda *a, **k: SimpleNamespace(status_code=200, text="{\\"access_token\\":\\"new\\",\\"token_type\\":\\"Bearer\\"}", headers={})\nt = s.refresh_token("https://provider.example/token")\nresult = t["access_token"] == "new" and t["refresh_token"] == "refresh"'),
    ("oauth2_request_and_hook", 'import requests\nfrom requests_oauthlib import OAuth2Session\ns = OAuth2Session("client", token={"access_token":"token", "token_type":"Bearer"})\ntry:\n    s.register_compliance_hook("unsupported", lambda value: value)\n    result = False\nexcept ValueError:\n    seen = {}\n    old = requests.sessions.Session.request\n    def fake(self, method, url, **k):\n        seen.update(k)\n        return "sentinel"\n    requests.sessions.Session.request = fake\n    try:\n        value = s.request("GET", "https://api.example/resource")\n    finally:\n        requests.sessions.Session.request = old\n    result = value == "sentinel" and seen["headers"]["Authorization"] == "Bearer token"'),
    ("compliance_fixes", 'import json\nfrom requests_oauthlib import OAuth2Session\nfrom requests_oauthlib.compliance_fixes.facebook import facebook_compliance_fix\nfrom requests_oauthlib.compliance_fixes.mailchimp import mailchimp_compliance_fix\nfrom requests_oauthlib.compliance_fixes.weibo import weibo_compliance_fix\nclass R:\n    def __init__(self, body, content_type="application/json"):\n        self.headers={"content-type":content_type}; self.status_code=200; self._content=body.encode()\n    @property\n    def text(self): return self._content.decode()\na = facebook_compliance_fix(OAuth2Session("client"))\na_hook = next(iter(a.compliance_hook["access_token_response"]))\nb = mailchimp_compliance_fix(OAuth2Session("client"))\nb_response = R("{\\"scope\\":null,\\"expires_in\\":0}")\nfor hook in b.compliance_hook["access_token_response"]: b_response = hook(b_response)\nc = weibo_compliance_fix(OAuth2Session("client"))\nc_hook = next(iter(c.compliance_hook["access_token_response"]))\nresult = json.loads(a_hook(R("access_token=token&expires=10", "text/plain")).text)["token_type"] == "Bearer" and json.loads(b_response.text) == {"expires_in":3600} and c._client.default_token_placement == "query" and json.loads(c_hook(R("{\\"access_token\\":\\"token\\"}")).text)["token_type"] == "Bearer"'),
]
def main() -> None:
    leaves = []
    for leaf_id, source in SCENARIOS:
        try:
            result = execute_script(source, timeout_sec=8.0)
            passed = result.ok and result.value is True
            leaves.append({"id": leaf_id, "status": "passed" if passed else "failed"})
        except Exception as error:
            leaves.append({"id": leaf_id, "status": "failed", "message": str(error)[:240]})
    print(json.dumps({"schema_version": "1.0", "leaves": leaves}, sort_keys=True))
if __name__ == "__main__":
    main()
