import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { extname, relative, resolve, sep } from "node:path";
import * as ts from "typescript";
export type Location = {
  file: string;
  line: number;
  column: number;
  endLine: number;
  endColumn: number;
};
export type Symbol = {
  module: string;
  name: string;
  export_name: string | null;
  qualified_name: string;
  kind: string;
  signature: string | null;
  source_location: Location;
  public: boolean;
  exported: boolean;
  re_exported: boolean;
  async: boolean;
  generator: boolean;
  dynamic_risk: string[];
};
export type Inventory = {
  schema_shape: string;
  language: "node";
  source_root: string;
  source_digest: string;
  scanner_identity: string;
  scanner_digest: string;
  modules: Symbol[];
  symbols: Symbol[];
  imports: { module: string; imported: string; line: number }[];
  tests: {
    module: string;
    name: string;
    source_location: Location;
    referenced_names: string[];
    assertion_kinds: string[];
  }[];
  cli_entries: string[];
  data_contracts: {
    module: string;
    name: string;
    kind: string;
    source_location: Location;
  }[];
  dependency_edges: {
    module: string;
    imported: string;
    line: number;
    external: boolean;
  }[];
  risk_flags: string[];
  syntax_diagnostics: string[];
  package: Record<string, unknown>;
  details: {
    node: {
      module_systems: string[];
      source_files: string[];
      test_files: string[];
    };
  };
  implementation_loc: number;
  test_loc: number;
  metrics: Record<string, number>;
  completeness: Record<string, boolean>;
};
type File = {
  relative: string;
  text: string;
  source: ts.SourceFile;
  test: boolean;
};
const EXTS = new Set([
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
]);
const TEST_DIRS = new Set(["test", "tests", "__tests__", "spec", "specs"]);
const SERVICE = new Set([
  "http",
  "https",
  "net",
  "tls",
  "dns",
  "dgram",
  "axios",
  "got",
  "undici",
  "node-fetch",
  "ws",
]);
const NATIVE = new Set([
  "bindings",
  "node-gyp",
  "node-pre-gyp",
  "ffi-napi",
  "nan",
]);
export function scanSource(input: string): Inventory {
  const root = resolve(input);
  if (!dir(root))
    throw Error(`source root must be a regular directory: ${input}`);
  const files = walkFiles(root)
    .filter((p) => EXTS.has(extname(p)))
    .map((p) => parse(root, p));
  if (!files.length)
    throw Error(`no JavaScript or TypeScript files found below ${input}`);
  const pkg = readPackage(root),
    symbols: Symbol[] = [],
    imports: { module: string; imported: string; line: number }[] = [],
    tests: Inventory["tests"] = [],
    contracts: Inventory["data_contracts"] = [],
    risks = new Set<string>(),
    systems = new Set<string>(),
    diagnostics: string[] = [];
  for (const f of files) {
    const exports = collectExports(f, imports, systems);
    for (const d of (
      f.source as ts.SourceFile & {
        parseDiagnostics?: readonly ts.Diagnostic[];
      }
    ).parseDiagnostics ?? [])
      diagnostics.push(diag(f.source, d));
    walk(f.source, (n) => {
      if (ts.isImportDeclaration(n) && ts.isStringLiteral(n.moduleSpecifier))
        recordImport(
          f,
          imports,
          risks,
          systems,
          n.moduleSpecifier.text,
          line(f.source, n),
        );
      if (
        ts.isExportDeclaration(n) &&
        n.moduleSpecifier &&
        ts.isStringLiteral(n.moduleSpecifier)
      )
        recordImport(
          f,
          imports,
          risks,
          systems,
          n.moduleSpecifier.text,
          line(f.source, n),
        );
      if (ts.isCallExpression(n)) {
        const c = name(n.expression);
        if (c === "eval" || c === "Function" || c === "global.eval")
          risks.add("dynamic-execution");
        if (c === "import") risks.add("dynamic-import");
        if (c === "fetch" || c.endsWith(".request") || c.endsWith(".connect"))
          risks.add("external-service");
        if (
          f.test &&
          /^(test|it|spec|describe)$/.test(c) &&
          n.arguments.length > 1
        ) {
          const label = ts.isStringLiteral(n.arguments[0])
            ? n.arguments[0].text
            : c;
          const cb = n.arguments[1];
          if (ts.isFunctionLike(cb)) tests.push(testInfo(f, cb, label));
        }
      }
      if (ts.isNewExpression(n) && name(n.expression) === "Function")
        risks.add("dynamic-execution");
      if (ts.isStringLiteral(n) && /generated by|auto-generated/i.test(n.text))
        risks.add("generated-code");
      if (
        (ts.isFunctionDeclaration(n) ||
          ts.isMethodDeclaration(n) ||
          ts.isArrowFunction(n) ||
          ts.isFunctionExpression(n) ||
          ts.isClassDeclaration(n)) &&
        !f.test
      ) {
        const s = symbol(f, n, exports);
        if (s) symbols.push(s);
      }
      if (
        (ts.isInterfaceDeclaration(n) ||
          ts.isTypeAliasDeclaration(n) ||
          ts.isEnumDeclaration(n)) &&
        !f.test &&
        n.name
      )
        contracts.push({
          module: mod(f),
          name: n.name.text,
          kind: ts.isInterfaceDeclaration(n)
            ? "interface"
            : ts.isTypeAliasDeclaration(n)
              ? "type"
              : "enum",
          source_location: loc(f, n),
        });
    });
  }
  inspectPackage(root, pkg, risks, systems);
  const ss = symbols.sort((a, b) =>
      `${a.module}:${a.source_location.line}:${a.qualified_name}`.localeCompare(
        `${b.module}:${b.source_location.line}:${b.qualified_name}`,
      ),
    ),
    tt = tests.sort((a, b) =>
      `${a.module}:${a.name}:${a.source_location.line}`.localeCompare(
        `${b.module}:${b.name}:${b.source_location.line}`,
      ),
    ),
    ii = imports.sort((a, b) =>
      `${a.module}:${a.line}:${a.imported}`.localeCompare(
        `${b.module}:${b.line}:${b.imported}`,
      ),
    ),
    sourceFiles = files
      .filter((f) => !f.test)
      .map((f) => f.relative)
      .sort(),
    testFiles = files
      .filter((f) => f.test)
      .map((f) => f.relative)
      .sort(),
    impl = files
      .filter((f) => !f.test)
      .reduce((n, f) => n + locCount(f.text), 0),
    testLoc = files
      .filter((f) => f.test)
      .reduce((n, f) => n + locCount(f.text), 0),
    badSyntax = diagnostics.length > 0;
  return {
    schema_shape: "api-inventory",
    language: "node",
    source_root: root,
    source_digest: digest(root, files),
    scanner_identity: "node-typescript-compiler-api",
    scanner_digest: `sha256:${createHash("sha256").update("node-typescript-compiler-api").digest("hex")}`,
    modules: ss,
    symbols: ss,
    imports: ii,
    tests: tt,
    cli_entries:
      pkg.bin && typeof pkg.bin === "object"
        ? Object.keys(pkg.bin as object).sort()
        : pkg.bin
          ? [pkg.name as string]
          : [],
    data_contracts: contracts.sort((a, b) =>
      `${a.module}:${a.name}`.localeCompare(`${b.module}:${b.name}`),
    ),
    dependency_edges: ii.map((i) => ({
      ...i,
      external: !i.imported.startsWith(".") && !i.imported.startsWith("/"),
    })),
    risk_flags: [...risks].sort(),
    syntax_diagnostics: diagnostics.sort(),
    package: pkg,
    details: {
      node: {
        module_systems: [...systems].sort(),
        source_files: sourceFiles,
        test_files: testFiles,
      },
    },
    implementation_loc: impl,
    test_loc: testLoc,
    metrics: {
      implementation_loc: impl,
      test_loc: testLoc,
      source_files: sourceFiles.length,
      test_files: testFiles.length,
      public_symbol_count: ss.filter((s) => s.public).length,
      test_count: tt.length,
      import_count: ii.length,
    },
    completeness: {
      dynamic: !risks.has("dynamic-execution") && !risks.has("dynamic-import"),
      generated: !risks.has("generated-code"),
      native: !risks.has("native-addon"),
      external_service: !risks.has("external-service"),
      unresolved: badSyntax,
      syntax: !badSyntax,
    },
  };
}
function collectExports(
  f: File,
  imports: { module: string; imported: string; line: number }[],
  systems: Set<string>,
): Map<string, string> {
  const e = new Map<string, string>();
  for (const st of f.source.statements) {
    if (hasExport(st)) {
      systems.add("esm");
      for (const d of declared(st)) {
        const n = declName(d);
        if (n) e.set(n, n);
      }
    }
    if (ts.isExportAssignment(st)) {
      systems.add("esm");
      e.set("default", "default");
    }
    if (ts.isExportDeclaration(st)) {
      systems.add("esm");
      if (st.exportClause && ts.isNamedExports(st.exportClause))
        for (const x of st.exportClause.elements)
          e.set(x.name.text, x.propertyName?.text ?? x.name.text);
    }
  }
  walk(f.source, (n) => {
    if (
      !ts.isBinaryExpression(n) ||
      n.operatorToken.kind !== ts.SyntaxKind.EqualsToken
    )
      return;
    const l = name(n.left);
    if (
      l !== "module.exports" &&
      !l.startsWith("exports.") &&
      !l.startsWith("module.exports.")
    )
      return;
    systems.add("commonjs");
    if (l === "module.exports" && ts.isObjectLiteralExpression(n.right))
      for (const p of n.right.properties)
        if (ts.isShorthandPropertyAssignment(p))
          e.set(String((p as any).name.text), String((p as any).name.text));
        else if (ts.isPropertyAssignment(p))
          e.set(
            p.name.getText(f.source),
            ts.isIdentifier(p.initializer)
              ? p.initializer.text
              : p.name.getText(f.source),
          );
        else
          e.set(
            l.split(".").at(-1)!,
            ts.isIdentifier(n.right)
              ? (n.right as ts.Identifier).text
              : l.split(".").at(-1)!,
          );
  });
  return e;
}
function symbol(f: File, n: ts.Node, e: Map<string, string>): Symbol | null {
  const name0 = declName(n);
  if (!name0) return null;
  const en =
    e.get(name0) ?? [...e.entries()].find(([, v]) => v === name0)?.[0] ?? null;
  const parent =
    n.parent && ts.isClassLike(n.parent) ? n.parent.name?.text : null;
  const q = `${mod(f)}.${parent ? parent + "." : ""}${name0}`,
    mods = ts.canHaveModifiers(n) ? (ts.getModifiers(n) ?? []) : [],
    async0 = mods.some((m) => m.kind === ts.SyntaxKind.AsyncKeyword),
    gen =
      ts.isFunctionLike(n) &&
      !!(n as ts.FunctionLikeDeclarationBase).asteriskToken;
  return {
    module: mod(f),
    name: name0,
    export_name: en,
    qualified_name: q,
    kind: ts.isClassDeclaration(n) ? "class" : parent ? "method" : "function",
    signature: signature(n, f.source),
    source_location: loc(f, n),
    public: !name0.startsWith("_") || !!en,
    exported: !!en,
    re_exported: false,
    async: async0,
    generator: gen,
    dynamic_risk: [],
  };
}
function testInfo(f: File, n: ts.Node, nm: string): Inventory["tests"][number] {
  const refs = new Set<string>(),
    asserts = new Set<string>();
  walk(n, (x) => {
    if (ts.isIdentifier(x)) refs.add(x.text);
    if (ts.isCallExpression(x)) {
      const c = name(x.expression);
      if (/^(assert|expect|strictEqual|deepStrictEqual)/.test(c))
        asserts.add("assertion");
      if (/raises|throws|rejects/.test(c)) asserts.add("exception");
      if (/readFile|writeFile|mkdir|unlink/.test(c)) asserts.add("filesystem");
    }
  });
  return {
    module: mod(f),
    name: nm,
    source_location: loc(f, n),
    referenced_names: [...refs].sort(),
    assertion_kinds: [...asserts].sort(),
  };
}
function recordImport(
  f: File,
  ii: { module: string; imported: string; line: number }[],
  r: Set<string>,
  s: Set<string>,
  v: string,
  l: number,
): void {
  ii.push({ module: mod(f), imported: v, line: l });
  const b = (v.startsWith("node:") ? v.slice(5) : v).split("/")[0];
  if (SERVICE.has(b)) r.add("external-service");
  if (NATIVE.has(b)) r.add("native-addon");
  if (b === "fs") r.add("filesystem-access");
  if (b === "child_process") r.add("process-access");
}
function inspectPackage(
  root: string,
  p: Record<string, unknown>,
  r: Set<string>,
  s: Set<string>,
): void {
  if (p.type === "module" || p.exports !== null) s.add("esm");
  if (p.type === "commonjs" || p.main !== null) s.add("commonjs");
  if (p.workspaces !== null) r.add("workspace");
  const scripts = p.scripts as Record<string, unknown> | undefined;
  if (
    scripts &&
    ["install", "preinstall", "postinstall"].some((k) => k in scripts)
  )
    r.add("postinstall");
  if (p.gypfile || p.binary || p.os || p.cpu) r.add("native-addon");
}
function readPackage(root: string): Record<string, unknown> {
  const p = (json(resolve(root, "package.json")) ?? {}) as Record<
      string,
      unknown
    >,
    l = json(resolve(root, "package-lock.json"));
  const manager =
    typeof p.packageManager === "string" ? p.packageManager : null;
  return {
    name: p.name ?? null,
    version: p.version ?? null,
    type: p.type ?? null,
    exports: p.exports ?? null,
    bin: p.bin ?? null,
    main: p.main ?? null,
    module: p.module ?? null,
    types: p.types ?? p.typings ?? null,
    files: p.files ?? null,
    workspaces: p.workspaces ?? null,
    scripts: p.scripts ?? null,
    package_manager: manager
      ? manager.split("@")[0]
      : exists(resolve(root, "package-lock.json"))
        ? "npm"
        : null,
    package_manager_version: manager?.slice(manager.indexOf("@") + 1) ?? null,
    lockfile:
      l && typeof l.lockfileVersion === "number"
        ? { name: "package-lock.json", version: l.lockfileVersion }
        : null,
  };
}
function parse(root: string, p: string): File {
  const text = readFileSync(p, "utf8"),
    rp = relative(root, p).split(sep).join("/");
  return {
    relative: rp,
    text,
    source: ts.createSourceFile(
      rp,
      text,
      ts.ScriptTarget.Latest,
      true,
      ts.ScriptKind.TSX,
    ),
    test:
      rp.split("/").some((x) => TEST_DIRS.has(x)) ||
      /\.(test|spec)\.[cm]?[jt]sx?$/.test(rp),
  };
}
function walk(n: ts.Node, v: (n: ts.Node) => void): void {
  v(n);
  n.forEachChild((c) => walk(c, v));
}
function declared(n: ts.Node): readonly ts.Node[] {
  return ts.isFunctionDeclaration(n) ||
    ts.isClassDeclaration(n) ||
    ts.isVariableStatement(n)
    ? ts.isVariableStatement(n)
      ? n.declarationList.declarations
      : [n]
    : [];
}
function declName(n: ts.Node): string | null {
  if (ts.isVariableDeclaration(n) && ts.isIdentifier(n.name))
    return n.name.text;
  if (
    ts.isFunctionDeclaration(n) ||
    ts.isClassDeclaration(n) ||
    ts.isMethodDeclaration(n) ||
    ts.isInterfaceDeclaration(n) ||
    ts.isTypeAliasDeclaration(n) ||
    ts.isEnumDeclaration(n)
  )
    return n.name?.getText() ?? null;
  if (
    (ts.isArrowFunction(n) || ts.isFunctionExpression(n)) &&
    ts.isVariableDeclaration(n.parent) &&
    ts.isIdentifier(n.parent.name)
  )
    return n.parent.name.text;
  return null;
}
function signature(n: ts.Node, s: ts.SourceFile): string | null {
  if (ts.isClassDeclaration(n)) return `class ${n.name?.text ?? "<anonymous>"}`;
  if (
    ts.isFunctionDeclaration(n) ||
    ts.isMethodDeclaration(n) ||
    ts.isArrowFunction(n) ||
    ts.isFunctionExpression(n)
  )
    return n.getText(s).split("{")[0].trim();
  return null;
}
function hasExport(n: ts.Node): boolean {
  return !!(
    ts.canHaveModifiers(n) &&
    ts.getModifiers(n)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
  );
}
function name(n: ts.Node): string {
  return ts.isIdentifier(n)
    ? n.text
    : ts.isPropertyAccessExpression(n)
      ? `${name(n.expression)}.${n.name.text}`
      : n.getText();
}
function loc(f: File, n: ts.Node): Location {
  const a = f.source.getLineAndCharacterOfPosition(n.getStart(f.source)),
    b = f.source.getLineAndCharacterOfPosition(n.getEnd());
  return {
    file: f.relative,
    line: a.line + 1,
    column: a.character + 1,
    endLine: b.line + 1,
    endColumn: b.character + 1,
  };
}
function line(s: ts.SourceFile, n: ts.Node): number {
  return s.getLineAndCharacterOfPosition(n.getStart(s)).line + 1;
}
function mod(f: File): string {
  return f.relative
    .replace(/\.(d\.)?(c|m)?[jt]sx?$/i, "")
    .replace(/\/index$/i, "")
    .replaceAll("/", ".");
}
function dir(p: string): boolean {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}
function exists(p: string): boolean {
  try {
    return statSync(p).isFile();
  } catch {
    return false;
  }
}
function json(p: string): Record<string, unknown> | null {
  try {
    const x = JSON.parse(readFileSync(p, "utf8"));
    return x && typeof x === "object" ? x : null;
  } catch {
    return null;
  }
}
function walkFiles(root: string): string[] {
  const out: string[] = [];
  const go = (d: string): void => {
    for (const e of readdirSync(d).sort()) {
      const p = resolve(d, e);
      if (e === "node_modules" || e === ".git" || e === "dist") continue;
      if (dir(p)) go(p);
      else out.push(p);
    }
  };
  go(root);
  return out;
}
function locCount(t: string): number {
  return t
    .split(/\r?\n/)
    .filter(
      (x) =>
        x.trim() &&
        !x.trim().startsWith("//") &&
        !x.trim().startsWith("/*") &&
        !x.trim().startsWith("*"),
    ).length;
}
function digest(root: string, fs: File[]): string {
  const h = createHash("sha256");
  for (const f of fs.sort((a, b) => a.relative.localeCompare(b.relative))) {
    const n = Buffer.from(f.relative),
      x = Buffer.from(f.text),
      z = Buffer.alloc(8);
    z.writeBigUInt64BE(BigInt(n.length));
    h.update(z).update(n);
    z.writeBigUInt64BE(BigInt(x.length));
    h.update(z).update(x);
  }
  return `sha256:${h.digest("hex")}`;
}
function parseDiagnostics(s: ts.SourceFile): readonly ts.Diagnostic[] {
  return (
    (s as ts.SourceFile & { parseDiagnostics?: readonly ts.Diagnostic[] })
      .parseDiagnostics ?? []
  );
}
function diag(s: ts.SourceFile, d: ts.Diagnostic): string {
  const p =
    d.start === undefined
      ? { line: 0, character: 0 }
      : s.getLineAndCharacterOfPosition(d.start);
  return `${s.fileName}:${p.line + 1}:${p.character + 1}: ${ts.flattenDiagnosticMessageText(d.messageText, " ")}`;
}
