FROM --platform=linux/amd64 python@sha256:2c941e860699f878900b0edc2403613c234d4b32eda3cc9fa7036991a2a63c4a

RUN pip install --no-cache-dir annotated-doc==0.0.4 markdown-it-py==4.0.0 mdurl==0.1.2 pdm-backend==2.4.9 pygments==2.20.0 rich==15.0.0 setuptools==80.9.0 shellingham==1.5.4 wheel==0.45.1

WORKDIR /workspace
