import assert from 'node:assert/strict'
import test from 'node:test'
import {callAdapter, callAdapterExpectError} from './test_client.mjs'

test('api reports package metadata and root exports', () => {
  assert.deepEqual(callAdapter({op: 'api'}), {name: 'mdast-util-mdxjs-esm', version: '2.0.1', exports: ['mdxjsEsmFromMarkdown', 'mdxjsEsmToMarkdown'], from: {enter: ['mdxjsEsm'], exit: ['mdxjsEsm', 'mdxjsEsmData']}, to: {handlers: ['mdxjsEsm']}})
})
test('factories return independent extension objects', () => assert.deepEqual(callAdapter({op: 'factories'}), {fromIndependent: true, toIndependent: true, handlersShared: true}))
test('from enter exposes the mdxjsEsm enter handler', () => assert.deepEqual(callAdapter({op: 'from-enter', token: {kind: 'start'}}).calls[0].node, {type: 'mdxjsEsm', value: ''}))
test('from enter forwards the token', () => assert.deepEqual(callAdapter({op: 'from-enter', token: {kind: 'start'}}).calls[0].token, {kind: 'start'}))
test('from enter buffers source text', () => assert.deepEqual(callAdapter({op: 'from-enter', token: {}}).calls[1], {kind: 'buffer'}))
test('from exit resumes before exiting', () => assert.deepEqual(callAdapter({op: 'from-exit', value: 'import x from "y"', token: {kind: 'end'}}).calls.map((call) => call.kind), ['resume', 'exit']))
test('from exit assigns the resumed value', () => assert.equal(callAdapter({op: 'from-exit', value: 'export const x = 1'}).node.value, 'export const x = 1'))
test('from exit forwards the exit token', () => assert.deepEqual(callAdapter({op: 'from-exit', value: '', token: {kind: 'end'}}).calls[1].token, {kind: 'end'}))
test('from exit copies a truthy ESTree result', () => assert.deepEqual(callAdapter({op: 'from-exit', value: 'x', estree: {type: 'Program', body: []}}).node.data, {estree: {type: 'Program', body: []}}))
test('from exit omits data without an ESTree result', () => assert.equal(Object.hasOwn(callAdapter({op: 'from-exit', value: 'x'}).node, 'data'), false))
test('from exit preserves an empty source value', () => assert.equal(callAdapter({op: 'from-exit', value: ''}).node.value, ''))
test('from exit preserves structured ESTree fields', () => assert.deepEqual(callAdapter({op: 'from-exit', value: 'x', estree: {type: 'Program', sourceType: 'module', body: [{type: 'ImportDeclaration'}]}}).node.data.estree.sourceType, 'module'))
test('from data delegates enter data first', () => assert.deepEqual(callAdapter({op: 'from-data', token: {kind: 'data'}}).events.map((event) => event.kind), ['enter', 'exit']))
test('from data forwards the token to enter', () => assert.deepEqual(callAdapter({op: 'from-data', token: {kind: 'data'}}).events[0].token, {kind: 'data'}))
test('from data forwards the token to exit', () => assert.deepEqual(callAdapter({op: 'from-data', token: {kind: 'data'}}).events[1].token, {kind: 'data'}))
test('to markdown exposes the mdxjsEsm handler', () => assert.deepEqual(callAdapter({op: 'api'}).to.handlers, ['mdxjsEsm']))
test('to markdown returns a source value', () => assert.deepEqual(callAdapter({op: 'to-markdown', node: {type: 'mdxjsEsm', value: 'import x from "y"'}}), {value: 'import x from "y"'}))
test('to markdown returns empty text for a missing value', () => assert.deepEqual(callAdapter({op: 'to-markdown', node: {type: 'mdxjsEsm'}}), {value: ''}))
test('to markdown returns empty text for null', () => assert.deepEqual(callAdapter({op: 'to-markdown', node: {type: 'mdxjsEsm', value: null}}), {value: ''}))
test('to markdown returns empty text for false', () => assert.deepEqual(callAdapter({op: 'to-markdown', node: {type: 'mdxjsEsm', value: false}}), {value: ''}))
test('to markdown preserves a truthy non-string value', () => assert.deepEqual(callAdapter({op: 'to-markdown', node: {type: 'mdxjsEsm', value: 7}}), {value: 7}))
test('to markdown preserves whitespace exactly', () => assert.deepEqual(callAdapter({op: 'to-markdown', node: {type: 'mdxjsEsm', value: '\n import x\n'}}), {value: '\n import x\n'}))
test('factories are repeatable after handler use', () => assert.deepEqual(callAdapter({op: 'from-enter', token: {id: 1}}).calls[0].node, {type: 'mdxjsEsm', value: ''}))
test('from enter accepts an empty token', () => assert.equal(callAdapter({op: 'from-enter'}).calls.length, 2))
test('from data accepts an empty token', () => assert.equal(callAdapter({op: 'from-data'}).events.length, 2))
test('to markdown accepts an empty node', () => assert.deepEqual(callAdapter({op: 'to-markdown'}), {value: ''}))
test('adapter rejects an unknown operation', () => assert.equal(callAdapterExpectError({op: 'unknown'}).message, 'unsupported operation: unknown'))
test('adapter rejects a missing operation', () => assert.equal(callAdapterExpectError({}).message, 'op must be a string'))
test('adapter rejects an array request', () => assert.equal(callAdapterExpectError([]).message, 'request must be an object'))
test('adapter rejects a null request', () => assert.equal(callAdapterExpectError(null).message, 'request must be an object'))
