import assert from 'node:assert/strict';
import test from 'node:test';
import {callCandidate, runCli} from './test_client.mjs';

const value = (input, options) => callCandidate('jsesc', options === undefined ? [input] : [input, options]);

test('package CLI reports the pinned version', () => assert.equal(runCli(['--version']).stdout.trim(), 'v3.0.2'));
test('CLI escapes a positional string', () => assert.equal(runCli(['föo']).stdout.trim(), 'f\\xF6o'));
test('CLI supports wrapping and double quotes', () => assert.equal(runCli(['--double-quotes', '--wrap'], 'a"b\n').stdout.trim(), '"a\\"b"'));
test('CLI parses object JSON', () => assert.equal(runCli(['--object'], '{"b":"♥","a":1}\n').stdout.trim(), "{'b':'\\u2665','a':1}"));
test('CLI pretty prints object JSON', () => assert.equal(runCli(['--pretty'], '{"a":1}\n').stdout.trim(), "{\n\t'a': 1\n}"));
test('plain ASCII is unchanged', () => assert.equal(value('foo bar'), 'foo bar'));
test('single quote is escaped', () => assert.equal(value("'\"`"), "\\'\"`"));
test('short control escapes are used', () => assert.equal(value('\\\b\f\n\r\t'), String.raw`\\\b\f\n\r\t`));
test('NUL before text uses zero escape', () => assert.equal(value('a\0b'), 'a\\0b'));
test('NUL before digit uses hexadecimal escape', () => assert.equal(value(`a${String.fromCharCode(0)}1`), 'a\\x001'));
test('Latin-1 characters use hex escapes', () => assert.equal(value('föo bår'), 'f\\xF6o b\\xE5r'));
test('BMP Unicode uses four hex digits', () => assert.equal(value('♥'), '\\u2665'));
test('astral Unicode uses surrogate escapes by default', () => assert.equal(value('𝌆'), '\\uD834\\uDF06'));
test('lone high surrogate is escaped', () => assert.equal(value('\uD800'), '\\uD800'));
test('lone low surrogate is escaped', () => assert.equal(value('\uDC00'), '\\uDC00'));
test('double quotes can wrap', () => assert.equal(value('a"b', {quotes: 'double', wrap: true}), '"a\\"b"'));
test('backticks escape interpolation', () => assert.equal(value('foo${1+1}`', {quotes: 'backtick', wrap: true}), '`foo\\${1+1}\\``'));
test('escapeEverything escapes ASCII', () => assert.equal(value('AZ09 !', {escapeEverything: true}), '\\x41\\x5A\\x30\\x39\\x20\\x21'));
test('minimal preserves printable Unicode', () => assert.equal(value('a♥\u00A0𝌆', {minimal: true}), 'a♥\\xA0𝌆'));
test('ES6 uses code point escapes', () => assert.equal(value('a𝌆💩b', {es6: true}), 'a\\u{1D306}\\u{1F4A9}b'));
test('lowercase hex is honored', () => assert.equal(value('föo♥𝌆', {lowercaseHex: true}), 'f\\xf6o\\u2665\\ud834\\udf06'));
test('script context escapes etago', () => assert.equal(value('"<!--<script></script><style></style>"', {isScriptContext: true}), '"\\x3C!--<script><\\/script><style><\\/style>"'));
test('JSON script context uses Unicode less-than', () => assert.equal(value('<!--</script>', {isScriptContext: true, json: true}), '"\\u003C!--<\\/script>"'));
test('JSON uses double quotes and wrapping', () => assert.equal(value('foo\0\n♥', {json: true}), '"foo\\u0000\\n\\u2665"'));
test('explicit JSON wrap false wins', () => assert.equal(value('foo\0', {json: true, wrap: false}), 'foo\\u0000'));
test('decimal numbers are deterministic', () => assert.equal(value(42), '42'));
test('hexadecimal numbers use a prefix', () => assert.equal(value(0x1337, {numbers: 'hexadecimal'}), '0x1337'));
test('binary numbers use a prefix', () => assert.equal(value(42, {numbers: 'binary'}), '0b101010'));
test('octal numbers use a prefix', () => assert.equal(value(42, {numbers: 'octal'}), '0o52'));
test('negative hexadecimal numbers retain sign', () => assert.equal(value(-42, {numbers: 'hexadecimal'}), '0x-2A'));
test('numeric strings remain strings', () => assert.equal(value('42', {numbers: 'hexadecimal'}), '42'));
test('booleans use JavaScript literals', () => assert.equal(value(true), 'true'));
test('null uses the null literal', () => assert.equal(value(null), 'null'));
test('arrays preserve order', () => assert.equal(value(['a♥', 42, true, null]), "['a\\u2665',42,true,null]"));
test('nested arrays recurse', () => assert.equal(value([1, [2, 3], {b: '♥'}]), "[1,[2,3],{'b':'\\u2665'}]"));
test('empty arrays are compact', () => assert.equal(value([]), '[]'));
test('objects preserve own key order', () => assert.equal(value({foo: 'bar', heart: '♥'}), "{'foo':'bar','heart':'\\u2665'}"));
test('empty objects are compact', () => assert.equal(value({}), '{}'));
test('pretty arrays use supplied indentation', () => assert.equal(value([1, [2, 3]], {compact: false, indent: '  '}), '[\n  1,\n  [\n    2,\n    3\n  ]\n]'));
test('pretty objects use supplied indentation', () => assert.equal(value({foo: 'bar'}, {compact: false, indent: ' '}), "{\n 'foo': 'bar'\n}"));
test('indentLevel supplies an initial level', () => assert.equal(value({a: {b: 1}}, {compact: false, indent: '  ', indentLevel: 1}), "{\n    'a': {\n      'b': 1\n    }\n  }"));
test('JSON converts non-finite numbers to null', () => assert.equal(value(Infinity, {json: true}), 'null'));
test('JSON serializes finite numbers', () => assert.equal(value(3.5, {json: true}), '3.5'));
test('invalid quote option falls back to single', () => assert.equal(value('a', {quotes: 'invalid', wrap: true}), "'a'"));
test('JSON object output is valid JSON', () => assert.equal(value({a: '♥'}, {json: true}), '{"a":"\\u2665"}'));
test('minimal still escapes a quote when wrapped', () => assert.equal(value("a'b", {minimal: true, wrap: true}), "'a\\'b'"));
test('multiple CLI arguments are each emitted', () => assert.equal(runCli(['a', 'b']).stdout.trim(), 'a\nb'));
test('CLI reads stdin when provided', () => assert.equal(runCli([], '♥\n').stdout.trim(), '\\u2665'));
