import assert from 'node:assert/strict';
import {test} from 'node:test';
import {call, inventory, legacy} from './test_client.mjs';

test('package root has the frozen ESM shape', () => {
  assert.deepEqual(inventory(), {packageName: 'parse-json', packageVersion: '8.3.0', packageShape: true, runtimeEntry: true, declarationEntry: true, exportNames: ['JSONError', 'default']});
});
test('parses an object', () => assert.deepEqual(call({input: '{"foo": true}'}).value, {foo: true}));
test('parses arrays and primitives', () => assert.deepEqual([call({input: '[1,"x",null]'}).value, call({input: 'false'}).value], [[1, 'x', null], false]));
test('preserves nested JSON data', () => assert.deepEqual(call({input: '{"a":{"b":[1,2]},"empty":{}}'}).value, {a: {b: [1, 2]}, empty: {}}));
test('accepts surrounding whitespace', () => assert.equal(call({input: ' \n\t42 \r\n'}).value, 42));
test('does not share parse state across calls', () => assert.deepEqual([call({input: '{"a":1}'}).value, call({input: '{"b":2}'}).value], [{a: 1}, {b: 2}]));
test('supports filename as the second argument', () => { const error = call({input: '{', filename: 'settings.json'}).error; assert.match(error.message, /in settings\.json/); assert.equal(error.fileName, 'settings.json'); });
test('supports an explicit filename argument', () => { const error = call({input: '[,', filename: 'data.json'}).error; assert.equal(error.fileName, 'data.json'); assert.match(error.message, /in data\.json/); });
test('supports the filename overload in the second argument', () => { const error = call({input: '{', filenameSecond: 'overload.json'}).error; assert.equal(error.fileName, 'overload.json'); });
test('returns a JSONError with a native cause', () => { const error = call({input: '{"x":}'}).error; assert.equal(error.name, 'JSONError'); assert.equal(error.instanceOf, true); assert.equal(error.causeName, 'SyntaxError'); assert.equal(typeof error.causeMessage, 'string'); });
test('adds an empty-input explanation', () => { const error = call({input: ''}).error; assert.equal(error.message, 'Unexpected end of JSON input while parsing empty string'); assert.equal(error.rawCodeFrame, undefined); });
test('does not add the empty-input explanation to whitespace', () => assert.equal(call({input: ' '}).error.message, 'Unexpected end of JSON input'));
test('adds a code point to unexpected tokens', () => assert.match(call({input: 'a'}).error.message, /\\u\{61\}/));
test('keeps the filename out of successful values', () => assert.deepEqual(call({input: 'null', filename: 'null.json'}).value, null));
test('renders raw code frames', () => { const error = call({input: '{\n\t"foo": true,\n}'}).error; assert.match(error.rawCodeFrame, /> 3 \| \}/); assert.match(error.rawCodeFrame, /\^/); assert.equal(error.codeFrame.replace(/\u001B\[[0-9;]*m/g, ''), error.rawCodeFrame); });
test('renders one-based line and column locations', () => { const error = call({input: '{\n\t"foo": true,\n}'}).error; assert.match(error.message, /line 3 column 1/); });
test('handles a one-line syntax error frame', () => { const error = call({input: '{'}).error; assert.match(error.rawCodeFrame, /> 1 \| \{/); });
test('leaves locationless empty errors without a frame', () => assert.equal(call({input: ''}).error.codeFrame, undefined));
test('handles Unicode before an error using UTF-16 offsets', () => { const error = call({input: '{"😀":}'}).error; assert.equal(error.instanceOf, true); assert.equal(error.causeName, 'SyntaxError'); });
test('preserves the original cause message', () => { const error = call({input: '{"foo": true,}'}).error; assert.match(error.causeMessage, /JSON/); });
test('supports custom error filenames after construction through the overload', () => assert.equal(call({input: 'x', filename: 'foo.json'}).error.fileName, 'foo.json'));
test('legacy JSONError accepts a string', () => assert.deepEqual(legacy({message: 'custom'}), {name: 'JSONError', message: 'custom'}));
test('legacy JSONError appends its filename', () => assert.deepEqual(legacy({message: 'custom', filename: 'file.json'}), {name: 'JSONError', message: 'custom in file.json', fileName: 'file.json'}));
test('reviver can transform numeric values', () => assert.deepEqual(call({input: '{"n":2}', reviver: 'double'}).value, {n: 4}));
test('reviver can remove a property', () => assert.deepEqual(call({input: '{"keep":1,"remove":2}', reviver: 'key'}).value, {keep: 1}));
test('reviver can transform the root', () => assert.deepEqual(call({input: '{"x":1}', reviver: 'root'}).value, {wrapped: {x: 1}}));
test('reviver receives nested values before the root', () => assert.deepEqual(call({input: '[1,2]', reviver: 'double'}).value, [2, 4]));
test('keeps parse failures synchronous in the child contract', () => { const result = call({input: 'not json'}); assert.equal(result.ok, false); assert.equal(result.error.instanceOf, true); });
test('preserves punctuation in valid strings', () => assert.deepEqual(call({input: '{"text":"a:b,c;d"}'}).value, {text: 'a:b,c;d'}));
test('parses escaped Unicode strings', () => assert.equal(call({input: '"\\uD83D\\uDE00"'}).value, '😀'));
test('distinguishes null from an error', () => assert.deepEqual(call({input: 'null'}), {ok: true, value: null}));
test('reports error metadata without leaking candidate internals', () => { const error = call({input: ']' }).error; assert.equal(typeof error.message, 'string'); assert.equal(typeof error.causeMessage, 'string'); assert.equal(error.instanceOf, true); });
test('keeps valid calls deterministic', () => assert.equal(JSON.stringify(call({input: '{"a": [true, false]}'})), JSON.stringify(call({input: '{"a": [true, false]}'}))));
