import assert from 'node:assert/strict';
import test from 'node:test';
import {callCandidate} from './test_client.mjs';

test('exports the documented root API', () => assert.deepEqual(callCandidate('exports'), {default: 'function', buffer: 'function', arrayBuffer: 'function', array: 'function', maxBufferError: 'MaxBufferError'}));
test('reads text chunks in order', () => assert.equal(callCandidate('textBasic'), 'hello world'));
test('decodes UTF-8 split across chunks', () => assert.equal(callCandidate('textUtf8Split'), '🌍'));
test('decodes ArrayBuffer text chunks', () => assert.equal(callCandidate('textArrayBuffer'), 'hi'));
test('respects typed-array byte offsets for text', () => assert.equal(callCandidate('textTypedOffset'), 'hello'));
test('reads a Web ReadableStream as text', () => assert.equal(callCandidate('textWeb'), 'web stream'));
test('reads an async iterable as text', () => assert.equal(callCandidate('textAsync'), 'async iterable'));
test('enforces text maxBuffer and reports buffered data', () => assert.deepEqual(callCandidate('textMax'), {name: 'MaxBufferError', message: 'maxBuffer exceeded', bufferedData: 'abc'}));
test('returns a Buffer for mixed text and binary chunks', () => assert.deepEqual(callCandidate('bufferBasic'), {type: 'Buffer', data: [...Buffer.from('hello world')]}));
test('respects typed-array byte offsets for Buffer output', () => assert.deepEqual(callCandidate('bufferTypedOffset'), {type: 'Buffer', data: [97, 98, 99]}));
test('converts ArrayBuffer chunks to Buffer', () => assert.deepEqual(callCandidate('bufferArrayBuffer'), {type: 'Buffer', data: [1, 2, 3]}));
test('enforces Buffer maxBuffer', () => assert.deepEqual(callCandidate('bufferMax'), {name: 'MaxBufferError', bufferedData: {type: 'Buffer', data: [1, 2, 3]}}));
test('attaches buffered Buffer data to stream errors', () => assert.deepEqual(callCandidate('bufferError'), {name: 'Error', message: 'boom', bufferedData: {type: 'Buffer', data: [...Buffer.from('partial')]}}));
test('returns exact ArrayBuffer bytes', () => assert.deepEqual(callCandidate('arrayBufferBasic'), {type: 'ArrayBuffer', data: [97, 98, 99]}));
test('respects typed-array byte offsets for ArrayBuffer output', () => assert.deepEqual(callCandidate('arrayBufferTypedOffset'), {type: 'ArrayBuffer', data: [10, 11, 12]}));
test('enforces ArrayBuffer byte maxBuffer', () => assert.deepEqual(callCandidate('arrayBufferMax'), {name: 'MaxBufferError', bufferedData: {type: 'ArrayBuffer', data: [1, 2]}}));
test('preserves array element order', () => assert.deepEqual(callCandidate('arrayValues'), ['a', 'b', 'c']));
test('preserves object-mode values in arrays', () => assert.deepEqual(callCandidate('arrayObjects'), [{id: 1}, {id: 2}]));
test('preserves mixed object-mode chunks', () => assert.deepEqual(callCandidate('arrayMixed'), ['a', {type: 'Buffer', data: [98]}, {id: 3}]));
test('measures array maxBuffer in elements', () => assert.deepEqual(callCandidate('arrayMax'), {name: 'MaxBufferError', bufferedData: [1, 2]}));
test('reads an already closed Web stream', () => assert.equal(callCandidate('webEnded'), ''));
test('reads binary Web stream chunks as ArrayBuffer', () => assert.deepEqual(callCandidate('webArrayBuffer'), {type: 'ArrayBuffer', data: [4, 5]}));
test('reads Web stream chunks into an array', () => assert.deepEqual(callCandidate('webArray'), ['x', 'y']));
test('supports object-mode async iterables', () => assert.deepEqual(callCandidate('asyncObjects'), [{kind: 'a'}, {kind: 'b'}]));
test('reads an already ended Node stream', () => assert.equal(callCandidate('nodeEnded'), ''));
test('supports concurrent readers of one Node stream', () => assert.deepEqual(callCandidate('concurrent'), ['same', 'same']));
test('attaches buffered text data to stream errors', () => assert.deepEqual(callCandidate('textError'), {name: 'Error', message: 'boom', bufferedData: 'partial'}));
test('closes an async iterable when maxBuffer fails', () => assert.equal(callCandidate('asyncCleanup'), true));
test('rejects a non-stream first argument', () => assert.equal(callCandidate('invalidInput').name, 'TypeError'));
test('rejects object chunks for text output', () => assert.equal(callCandidate('objectText').name, 'Error'));
