# ruff: noqa: E501
import json

from nl2repobench.verification.candidate_client import execute_script

CASES = [
('exports', "import starlette; from starlette import status; from starlette.datastructures import URL; assert starlette.__version__ == '1.6.0'; assert status.HTTP_200_OK == 200; assert URL('https://example.test').hostname == 'example.test'; result=True"),
('url', "from starlette.datastructures import URL, URLPath; u=URL('https://user:secret@example.test:8443/items?tag=a&tag=b&empty='); assert u.scheme=='https' and u.hostname=='example.test' and u.port==8443; assert str(u.replace_query_params(q='hello world'))=='https://user:secret@example.test:8443/items?q=hello+world'; assert 'secret' not in repr(u); assert str(URLPath('/x',protocol='websocket').make_absolute_url('http://example.test'))=='ws://example.test/x'; result=True"),
('multidict', "from starlette.datastructures import MultiDict, QueryParams; m=MultiDict([('a','1'),('a','2'),('b','3')]); assert m['a']=='2' and m.getlist('a')==['1','2']; assert m.poplist('a')==['1','2'] and m.popitem()==('b','3'); q=QueryParams('q=hello+world&q=second'); assert q.getlist('q')==['hello world','second'] and str(q)=='q=hello+world&q=second'; result=True"),
('headers', "from starlette.datastructures import Headers; h=Headers({'X-Test':'one'}); assert h['x-test']=='one'; m=h.mutablecopy(); m['X-Test']='two'; m.append('x-test','three'); m.add_vary_header('Origin'); assert m.getlist('x-test')==['two','three'] and m['vary']=='Origin'; result=True"),
('state', "from starlette.datastructures import Address, Secret, State, CommaSeparatedStrings; s=State({'seed':1}); s.value='ok'; s['count']=2; assert s.seed==1 and s['value']=='ok' and Address('localhost',8000).port==8000; assert 'token' not in repr(Secret('token')); assert list(CommaSeparatedStrings('a, \"two, words\", c'))==['a','two, words','c']; result=True"),
('convertors', "import math; from uuid import UUID; from starlette.convertors import FloatConvertor,IntegerConvertor,PathConvertor,StringConvertor,UUIDConvertor; assert StringConvertor().to_string('abc')=='abc' and PathConvertor().to_string('a/b')=='a/b'; assert IntegerConvertor().convert('007')==7 and FloatConvertor().convert('2.5')==2.5; assert UUIDConvertor().convert('00000000-aaaa-ffff-9999-000000000000')==UUID('00000000-aaaa-ffff-9999-000000000000'); result=True"),
('routing', "from starlette.responses import PlainTextResponse; from starlette.routing import Match,Route,compile_path; regex,fmt,converters=compile_path('/users/{id:int}/files/{path:path}'); assert regex.match('/users/42/files/a/b').groupdict()=={'id':'42','path':'a/b'}; endpoint=lambda request: PlainTextResponse('ok'); r=Route('/items/{item_id:int}',endpoint,methods=['GET'],name='item'); scope={'type':'http','method':'GET','path':'/items/42','root_path':'','path_params':{}}; assert r.matches(scope)[0] is Match.FULL and r.matches({**scope,'method':'POST'})[0] is Match.PARTIAL; assert str(r.url_path_for('item',item_id=7))=='/items/7'; result=True"),
('response', "from starlette.responses import Response,PlainTextResponse,HTMLResponse,JSONResponse,RedirectResponse; r=Response('hello',status_code=201,media_type='text/plain',headers={'X-Test':'yes'}); assert r.body==b'hello' and r.headers['content-length']=='5' and r.headers['content-type']=='text/plain; charset=utf-8'; assert PlainTextResponse('ok').body==b'ok' and HTMLResponse('<b>x</b>').headers['content-type'].startswith('text/html'); assert JSONResponse({'ok':True}).body==b'{\"ok\":true}'; assert RedirectResponse('https://example.test/a path').headers['location'].endswith('/a%20path'); result=True"),
('cookies', "from starlette.responses import Response; from starlette.requests import cookie_parser; assert cookie_parser('a=1; b=two; flag; quoted=\"hello world\"')=={'a':'1','b':'two','':'flag','quoted':'hello world'}; r=Response('ok'); r.set_cookie('session','abc',httponly=True,samesite='strict'); r.delete_cookie('old'); assert len(r.headers.getlist('set-cookie'))==2 and 'HttpOnly' in r.headers.getlist('set-cookie')[0]; result=True"),
('response-asgi', "import asyncio; from starlette.responses import JSONResponse; exec(\"async def main():\"+chr(10)+\" messages=[]\"+chr(10)+\" async def send(m): messages.append(m)\"+chr(10)+\" async def receive(): return {'type':'http.disconnect'}\"+chr(10)+\" await JSONResponse({'ok':True},status_code=202)({'type':'http'},receive,send)\"+chr(10)+\" assert messages[0]['status']==202 and messages[1]['body']==b'{\\\"ok\\\":true}'\"); asyncio.run(main()); result=True"),
('streaming', "import asyncio; from starlette.responses import StreamingResponse; exec(\"async def main():\"+chr(10)+\" messages=[]\"+chr(10)+\" async def send(m): messages.append(m)\"+chr(10)+\" async def receive(): return {'type':'http.disconnect'}\"+chr(10)+\" await StreamingResponse(['one',b'two'])({'type':'http','asgi':{'spec_version':'2.4'}},receive,send)\"+chr(10)+\" assert [m['body'] for m in messages[1:]]==[b'one',b'two',b''] and messages[-1]['more_body'] is False\"); asyncio.run(main()); result=True"),
('ranges', "from starlette.responses import FileResponse,MalformedRangeHeader,RangeNotSatisfiable; assert FileResponse._parse_range_header('bytes=0-4',10)==[(0,5)]; assert FileResponse._parse_range_header('bytes=-3',10)==[(7,10)]; assert FileResponse._parse_range_header('bytes=0-2,2-5',10)==[(0,6)]; result=True"),
('request', "import asyncio; from starlette.requests import Request; exec(\"async def main():\"+chr(10)+\" messages=iter([{'type':'http.request','body':b'{\\\"a\\\":','more_body':True},{'type':'http.request','body':b'1}','more_body':False}])\"+chr(10)+\" async def receive(): return next(messages)\"+chr(10)+\" scope={'type':'http','method':'POST','scheme':'http','server':('example.test',80),'path':'/submit','query_string':b'q=x','headers':[(b'host',b'example.test'),(b'cookie',b'sid=abc')],'client':('127.0.0.1',1234)}\"+chr(10)+\" r=Request(scope,receive); assert r.method=='POST' and r.query_params['q']=='x' and r.cookies=={'sid':'abc'}; assert await r.body()==b'{\\\"a\\\":1}' and await r.json()=={'a':1} and r.client.host=='127.0.0.1'\"); asyncio.run(main()); result=True"),
('stream-consumption', "import asyncio; from starlette.requests import Request; exec(\"async def main():\"+chr(10)+\" messages=iter([{'type':'http.request','body':b'a','more_body':True},{'type':'http.request','body':b'b','more_body':False}])\"+chr(10)+\" async def receive(): return next(messages)\"+chr(10)+\" r=Request({'type':'http','method':'POST','path':'/','headers':[],'query_string':b''},receive); assert [x async for x in r.stream()]==[b'a',b'b',b'']\"+chr(10)+\" try: [x async for x in r.stream()]\"+chr(10)+\" except RuntimeError as exc: assert str(exc)=='Stream consumed'\"+chr(10)+\" else: raise AssertionError('stream reused')\"); asyncio.run(main()); result=True"),
('exceptions', "from starlette.exceptions import HTTPException,WebSocketException; h=HTTPException(404,detail='missing',headers={'x-reason':'test'}); w=WebSocketException(code=1008,reason='denied'); assert h.status_code==404 and h.detail=='missing' and h.headers['x-reason']=='test'; assert w.code==1008 and w.reason=='denied'; result=True"),
('cors', "from starlette.datastructures import Headers; from starlette.middleware.cors import CORSMiddleware; app=lambda scope,receive,send: None; m=CORSMiddleware(app,allow_origins=['https://client.test'],allow_methods=['GET','POST'],allow_headers=['x-token'],allow_credentials=True,max_age=120); good=m.preflight_response(Headers(raw=[(b'origin',b'https://client.test'),(b'access-control-request-method',b'POST'),(b'access-control-request-headers',b'x-token')])); bad=m.preflight_response(Headers(raw=[(b'origin',b'https://evil.test'),(b'access-control-request-method',b'DELETE')])); assert good.status_code==200 and good.headers['access-control-allow-origin']=='https://client.test' and bad.status_code==400; result=True"),
('cors-simple', "import asyncio; from starlette.middleware.cors import CORSMiddleware; exec(\"async def app(scope,receive,send):\"+chr(10)+\" await send({'type':'http.response.start','status':200,'headers':[]})\"+chr(10)+\" await send({'type':'http.response.body','body':b'ok'})\"); m=CORSMiddleware(app,allow_origins=['https://client.test'],expose_headers=['x-total']); exec(\"async def main():\"+chr(10)+\" messages=[]\"+chr(10)+\" async def receive(): return {'type':'http.disconnect'}\"+chr(10)+\" async def send(x): messages.append(x)\"+chr(10)+\" await m({'type':'http','method':'GET','headers':[(b'origin',b'https://client.test')]},receive,send)\"+chr(10)+\" headers=dict((k.decode(),v.decode()) for k,v in messages[0]['headers']); assert headers['access-control-allow-origin']=='https://client.test' and headers['access-control-expose-headers']=='x-total'\"); asyncio.run(main()); result=True"),
('concurrency', "import asyncio; from starlette.concurrency import run_in_threadpool,iterate_in_threadpool; exec(\"async def main():\"+chr(10)+\" assert await run_in_threadpool(lambda x:x+1,4)==5\"+chr(10)+\" assert [x async for x in iterate_in_threadpool(iter([1,2,3]))]==[1,2,3]\"); asyncio.run(main()); result=True"),
('background', "import asyncio; from starlette.background import BackgroundTask,BackgroundTasks; events=[]; exec(\"def add(x): events.append(x)\"+chr(10)+\"async def add_async(x): events.append(x)\"+chr(10)+\"async def main():\"+chr(10)+\" await BackgroundTask(add,'sync')()\"+chr(10)+\" tasks=BackgroundTasks(); tasks.add_task(add_async,'async'); tasks.add_task(add,'last'); await tasks()\"); asyncio.run(main()); assert events==['sync','async','last']; result=True"),
('determinism', "from starlette.datastructures import URL,QueryParams,Headers; assert [str(URL('https://e.test/a?b=2&a=1').replace_query_params(z=3)) for _ in range(3)]==['https://e.test/a?z=3']*3; assert [str(QueryParams([('b','2'),('a','1')])) for _ in range(3)]==['b=2&a=1']*3; assert Headers({'X':'1'}).raw==[(b'x',b'1')]; result=True"),
('status', "from starlette import status; assert status.HTTP_200_OK==200 and status.HTTP_404_NOT_FOUND==404 and status.HTTP_500_INTERNAL_SERVER_ERROR==500; result=True"),
('middleware-export', "from starlette.middleware import Middleware; from starlette.middleware.cors import CORSMiddleware; app=lambda scope,receive,send: None; m=Middleware(CORSMiddleware,allow_origins=['*']); assert m.cls is CORSMiddleware and m.kwargs=={'allow_origins':['*']}; result=True"),
('config-and-auth', "from starlette.config import Config; from starlette.authentication import AuthCredentials,SimpleUser,UnauthenticatedUser; import os; os.environ['STARLETTE_TEST_VALUE']='yes'; c=Config('.missing-starlette-config'); assert c('STARLETTE_TEST_VALUE',cast=str)=='yes'; creds=AuthCredentials(['authenticated','admin']); assert creds.scopes==['authenticated','admin']; assert SimpleUser('Ada').display_name=='Ada' and not UnauthenticatedUser().is_authenticated; result=True"),
('websocket-and-status', "from starlette.websockets import WebSocketDisconnect,WebSocketState; from starlette import status; assert WebSocketState.CONNECTING.value==0 and WebSocketState.CONNECTED.value==1; exc=WebSocketDisconnect(code=1008,reason='denied'); assert exc.code==1008 and exc.reason=='denied'; assert status.HTTP_418_IM_A_TEAPOT==418; result=True"),
]

def main():
    leaves=[]
    for case_id, source in CASES:
        result=execute_script(source, timeout_sec=15.0)
        if result.ok and result.value is True:
            leaves.append({'id':case_id,'status':'passed'})
        else:
            leaves.append({'id':case_id,'status':'failed','message':(result.exception_message or 'false')[-1000:]})
    print(json.dumps({'schema_version':'1.0','leaves':leaves}, sort_keys=True))

if __name__ == '__main__':
    raise SystemExit(main() or 0)
