import assert from 'node:assert/strict';
import {test} from 'node:test';
import {call} from './test_client.mjs';
const u8=values=>({$uint8array:values});
const value=(name,args)=>{const r=call(name,args); assert.equal(r.ok,true,r.error); return r.value;};
const failed=(name,args)=>{const r=call(name,args); assert.equal(r.ok,false); return r;};
const bytes=x=>{assert.equal(x.$type,'Uint8Array'); return x.values;};
test('package identity and exports',()=>{assert.deepEqual(value('isUint8Array',[u8([])]),true); assert.equal(value('isUint8Array',[{}]),false);});
test('isUint8Array rejects other types',()=>assert.equal(value('isUint8Array',[{$uint16array:[1]}]),false));
test('assertUint8Array accepts bytes',()=>assert.deepEqual(value('assertUint8Array',[u8([])]),{$type:'undefined'}));
test('assertUint8Array rejects invalid values',()=>assert.equal(failed('assertUint8Array',[1]).exception_type,'TypeError'));
test('assertUint8ArrayOrArrayBuffer accepts both',()=>{value('assertUint8ArrayOrArrayBuffer',[u8([])]); value('assertUint8ArrayOrArrayBuffer',[{$arraybuffer:[1]}]);});
test('assertUint8ArrayOrArrayBuffer rejects invalid values',()=>assert.equal(failed('assertUint8ArrayOrArrayBuffer',[null]).exception_type,'TypeError'));
test('toUint8Array supports typed arrays',()=>assert.deepEqual(bytes(value('toUint8Array',[{$uint16array:[0x1234]}])),[0x34,0x12]));
test('toUint8Array supports buffers and views',()=>{assert.deepEqual(bytes(value('toUint8Array',[{$arraybuffer:[1,2]}])),[1,2]); assert.deepEqual(bytes(value('toUint8Array',[{$dataview:[3,4]}])),[3,4]);});
test('toUint8Array rejects unsupported values',()=>assert.equal(failed('toUint8Array',[123]).exception_type,'TypeError'));
test('concat handles normal and empty input',()=>{assert.deepEqual(bytes(value('concatUint8Arrays',[[u8([1]),u8([2,3])]])),[1,2,3]); assert.deepEqual(bytes(value('concatUint8Arrays',[[]])),[]);});
test('concat honors explicit length',()=>assert.deepEqual(bytes(value('concatUint8Arrays',[[u8([1,2])],4])),[1,2,0,0]));
test('concat validates members',()=>assert.equal(failed('concatUint8Arrays',[[1]]).exception_type,'TypeError'));
test('equality compares content and length',()=>{assert.equal(value('areUint8ArraysEqual',[u8([1]),u8([1])]),true); assert.equal(value('areUint8ArraysEqual',[u8([1]),u8([2])]),false); assert.equal(value('areUint8ArraysEqual',[u8([1]),u8([1,0])]),false);});
test('comparison is lexicographic',()=>{assert.equal(value('compareUint8Arrays',[u8([1]),u8([1])]),0); assert.equal(value('compareUint8Arrays',[u8([1]),u8([2])]),-1); assert.equal(value('compareUint8Arrays',[u8([2]),u8([1])]),1);});
test('comparison orders prefix lengths',()=>assert.equal(value('compareUint8Arrays',[u8([1]),u8([1,0])]),-1));
test('string conversions use UTF8',()=>{assert.deepEqual(bytes(value('stringToUint8Array',['Hello'])),[72,101,108,108,111]); assert.equal(value('uint8ArrayToString',[u8([72,105])]),'Hi');});
test('string decoding supports ArrayBuffer and encoding',()=>{assert.equal(value('uint8ArrayToString',[{$arraybuffer:[72,105]}]),'Hi'); assert.equal(value('uint8ArrayToString',[u8([207,240,232,226,229,242]),'windows-1251']),'Привет');});
test('string conversion validates inputs',()=>assert.equal(failed('stringToUint8Array',[1]).exception_type,'TypeError'));
test('standard Base64 round trips',()=>{const s=value('uint8ArrayToBase64',[u8([72,101,108,108,111])]); assert.equal(s,'SGVsbG8='); assert.deepEqual(bytes(value('base64ToUint8Array',[s])),[72,101,108,108,111]);});
test('Base64URL round trips without padding',()=>{const s=value('uint8ArrayToBase64',[u8([251,255,239]),{urlSafe:true}]); assert.equal(s,'-__v'); assert.deepEqual(bytes(value('base64ToUint8Array',[s])),[251,255,239]);});
test('Base64 handles empty and large chunked input',()=>{assert.equal(value('uint8ArrayToBase64',[u8([])]),''); assert.deepEqual(bytes(value('base64ToUint8Array',[''])),[]); const s=value('uint8ArrayToBase64',[{$uint8arrayRepeat:[65535,65]}]); assert.equal(s.length,87380);});
test('string Base64 preserves Unicode',()=>assert.equal(value('base64ToString',[value('stringToBase64',['a Ā 𐀀 文 🦄'])]),'a Ā 𐀀 文 🦄'));
test('Base64 validates strings',()=>assert.equal(failed('base64ToUint8Array',[1]).exception_type,'TypeError'));
test('hex conversion uses lowercase and accepts uppercase',()=>{assert.equal(value('uint8ArrayToHex',[u8([0,15,255])]),'000fff'); assert.deepEqual(bytes(value('hexToUint8Array',['aB00ff'])),[171,0,255]);});
test('hex rejects odd length',()=>assert.match(failed('hexToUint8Array',['a']).message,/Invalid Hex string length/));
test('hex rejects invalid characters',()=>assert.match(failed('hexToUint8Array',['0G']).message,/Invalid Hex character/));
test('big endian reads 1 through 6 bytes',()=>{for(let n=1;n<=6;n++){const a=[0x12,0x34,0x56,0x78,0x90,0xab].slice(0,n); const e=a.reduce((x,b)=>x*256+b,0); assert.equal(value('getUintBE',[{$dataview:a}]),e);}});
test('big endian unsupported length is undefined',()=>assert.deepEqual(value('getUintBE',[{$dataview:[]}]),{$type:'undefined'}));
test('indexOf and includes search byte sequences',()=>{assert.equal(value('indexOf',[u8([1,2,3,4]),u8([2,3])]),1); assert.equal(value('indexOf',[u8([1,2]),u8([])]),-1); assert.equal(value('includes',[u8([1,2,3]),u8([2,3])]),true); assert.equal(value('includes',[u8([1,2,3]),u8([3,2])]),false);});
