package nl2repobench.harness;
import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*;
public final class ContractMain {
  private static final String[] IDS={"basic-definite","bare-prefix","at-context","wildcard","scan","multi-index","slice","filter","function","blank-error"};
  private static final String[] OPS={"inspect","inspect","inspect","inspect","inspect","inspect","inspect","inspect","inspect","inspect"};
  private static final String[] INPUT={"$.store.book[0].title","store.book","@.items[1]","$.store.book[*].title","$..book.title","$.book[0,1]","$.book[0:2]","$.book[?(@.price > 1)]","$.book.length()"," "};
  private static final String[] EXPECT={"$.store.book[0].title|true","$.store.book|true","@.items[1]|true","$.store.book[*].title|false","$..book.title|false","$.book[0,1]|false","$.book[0:2]|false","$.book[?(@.price > 1)]|false","$.book.length()|false","InvalidPathException"};
  public static void main(String[] args) throws Exception { boolean[] ok=new boolean[IDS.length]; Process p=new ProcessBuilder(System.getProperty("nl2repobench.python","/usr/local/bin/python3"),"-I","-m","nl2repobench.verification.candidate_process_cli","--cwd","/tmp/java-harness","--uid","10001","--timeout-sec",System.getProperty("nl2repobench.candidate.timeout","300"),"--",System.getProperty("nl2repobench.java","/opt/java/openjdk/bin/java"),"-Xmx256m","-XX:MaxMetaspaceSize=128m","-cp",System.getProperty("nl2repobench.candidate.classpath","/tmp/java-harness/candidate-classes"),"nl2repobench.harness.CandidateMain").redirectError(ProcessBuilder.Redirect.INHERIT).start(); try(BufferedWriter in=new BufferedWriter(new OutputStreamWriter(p.getOutputStream(),StandardCharsets.UTF_8)); BufferedReader out=new BufferedReader(new InputStreamReader(p.getInputStream(),StandardCharsets.UTF_8))) { for(int i=0;i<IDS.length;i++) ok[i]=check(in,out,OPS[i],INPUT[i],EXPECT[i]); in.close(); } if(p.waitFor()!=0) Arrays.fill(ok,false); StringBuilder x=new StringBuilder("<e:events xmlns:e=\"https://schemas.opentest4j.org/reporting/events/0.1.0\" xmlns:j=\"https://schemas.junit.org/open-test-reporting\">"); x.append(start("c","Java JsonPath contract","[engine:nl2repobench]","CONTAINER",null)); boolean all=true; for(int i=0;i<IDS.length;i++){x.append(start("t"+i,IDS[i],"[engine:nl2repobench]/[test:"+IDS[i]+"]","TEST","c")).append(finish("t"+i,ok[i]?"SUCCESSFUL":"FAILED")); all&=ok[i];} x.append(finish("c","SUCCESSFUL")).append("</e:events>\n"); System.out.print(x); if(!all) System.exit(1); }
  private static boolean check(BufferedWriter in,BufferedReader out,String op,String v,String e)throws IOException{in.write(op+"\t"+Base64.getEncoder().encodeToString(v.getBytes(StandardCharsets.UTF_8)));in.newLine();in.flush();String l=out.readLine();if(l==null)return false;String[] f=l.split("\t",-1);if(f.length!=2)return false;String r=new String(Base64.getDecoder().decode(f[1]),StandardCharsets.UTF_8);return f[0].equals(e.equals("InvalidPathException")?"ERR":"OK")&&r.equals(e.equals("InvalidPathException")?e:e);}
  private static String start(String id,String n,String u,String t,String parent){return "<e:started id=\""+id+"\" name=\""+n+"\""+(parent==null?"":" parentId=\""+parent+"\"")+" time=\"2026-01-01T00:00:00Z\" uniqueId=\""+u+"\" type=\""+t+"\"/>";} private static String finish(String id,String s){return "<e:finished id=\""+id+"\" time=\"2026-01-01T00:00:00.010Z\"><j:result status=\""+s+"\"/></e:finished>";}
}
